### ISSUE TITLE
Error when trying to load

### ISSUE THREAD

**Issue by LoneWolfHT** [An0n3m0us/doorsplus#1]
```2019-06-01 14:35:46: ERROR[Main]: /root/minetest/bin/../builtin/game/register.lua:65: Name doors:hidden does not follow naming conventions: "doorsplus:" or ":" prefix required```

**Comment by An0n3m0us** [comment]
Sorry, I didn't see the notification.
It seems like you might have unzipped it into "doorsplus". You have to keep the name as "doors" so it overrides the default mod.
By the way, it's a minetest mod; put it in `~/.minetest/mods` not in `/usr/share/minetest/...`.

**Comment by An0n3m0us** [comment]
Paste this script in a terminal and it will automatically download the mod and move it to ~/.minetest/mods/.
`
cd /tmp/ && echo "Downloading doors.zip ..." && wget -q "https://github.com/An0n3m0us/doorsplus/releases/download/1.0/doors.zip" -O doors.zip && echo "Extracting doors.zip" && unzip -q doors.zip && echo "Removing doors.zip" && rm doors.zip && echo "Moving doors to ~/.minetest/mods/" && mv doors ~/.minetest/mods/
`

**Comment by LoneWolfHT** [comment]
Ah, I `git clone`'d it. I use a RUN_IN_PLACE dev build btw
(Closing to create a PR for this)
