### ISSUE TITLE
Cool Trees Doors Crash

### ISSUE THREAD

**Issue by ghost** [An0n3m0us/doorsplus#8]
Hi, your mod make my Cool Trees Doors to crash:

See:
https://github.com/runsy/cool_trees/issues/20

**Comment by An0n3m0us** [comment]
Sorry about that; I seem to have not received any notification on this issue.
I will look into this issue shortly.

**Comment by An0n3m0us** [comment]
Can you re-check now? I believe I have fixed it.

**Comment by sbrl** [comment]
Awesome, thanks! That seems to have fixed it :D

This issue can be closed now.

**Comment by An0n3m0us** [comment]
@sbrl Thank you for notifying me. It's good to hear that it's working now : )
